// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenWeather_screen_init(void)
{
    ui_ScreenWeather = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenWeather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBase = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelBase, 240);
    lv_obj_set_height(ui_PanelBase, 135);
    lv_obj_set_x(ui_PanelBase, 0);
    lv_obj_set_y(ui_PanelBase, -71);
    lv_obj_set_align(ui_PanelBase, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBase, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBase, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBase, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLocation = lv_label_create(ui_PanelBase);
    lv_obj_set_width(ui_LabelLocation, 113);
    lv_obj_set_height(ui_LabelLocation, 20);
    lv_obj_set_x(ui_LabelLocation, -16);
    lv_obj_set_y(ui_LabelLocation, -46);
    lv_obj_set_align(ui_LabelLocation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocation, "WuHan");
    lv_obj_set_style_text_align(ui_LabelLocation, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLocation, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLocation = lv_img_create(ui_PanelBase);
    lv_img_set_src(ui_ImageLocation, &ui_img_location2_png);
    lv_obj_set_width(ui_ImageLocation, 32);
    lv_obj_set_height(ui_ImageLocation, 32);
    lv_obj_set_x(ui_ImageLocation, 51);
    lv_obj_set_y(ui_ImageLocation, -46);
    lv_obj_set_align(ui_ImageLocation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLocation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLocation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTemp = lv_label_create(ui_PanelBase);
    lv_obj_set_width(ui_LabelTemp, 57);
    lv_obj_set_height(ui_LabelTemp, 40);
    lv_obj_set_x(ui_LabelTemp, -5);
    lv_obj_set_y(ui_LabelTemp, 3);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "11");
    lv_obj_set_style_text_align(ui_LabelTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDegree = lv_label_create(ui_PanelBase);
    lv_obj_set_width(ui_LabelDegree, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDegree, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDegree, 31);
    lv_obj_set_y(ui_LabelDegree, -14);
    lv_obj_set_align(ui_LabelDegree, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDegree, "°C");

    ui_LabelSplit = lv_label_create(ui_PanelBase);
    lv_obj_set_width(ui_LabelSplit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSplit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSplit, -2);
    lv_obj_set_y(ui_LabelSplit, 43);
    lv_obj_set_align(ui_LabelSplit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSplit, "|");

    ui_LabelWea = lv_label_create(ui_PanelBase);
    lv_obj_set_width(ui_LabelWea, 100);
    lv_obj_set_height(ui_LabelWea, 16);
    lv_obj_set_x(ui_LabelWea, -56);
    lv_obj_set_y(ui_LabelWea, 44);
    lv_obj_set_align(ui_LabelWea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWea, "Light Rain");
    lv_obj_set_style_text_align(ui_LabelWea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAir = lv_label_create(ui_PanelBase);
    lv_obj_set_width(ui_LabelAir, 100);
    lv_obj_set_height(ui_LabelAir, 16);
    lv_obj_set_x(ui_LabelAir, 53);
    lv_obj_set_y(ui_LabelAir, 44);
    lv_obj_set_align(ui_LabelAir, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAir, "Good");
    lv_obj_set_style_text_align(ui_LabelAir, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWeaTimePre = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelWeaTimePre, 240);
    lv_obj_set_height(ui_PanelWeaTimePre, 100);
    lv_obj_set_x(ui_PanelWeaTimePre, 0);
    lv_obj_set_y(ui_PanelWeaTimePre, 52);
    lv_obj_set_align(ui_PanelWeaTimePre, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWeaTimePre, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWeaTimePre, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWeaTimePre, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime1 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelTime1, 45);
    lv_obj_set_height(ui_LabelTime1, 16);
    lv_obj_set_x(ui_LabelTime1, -92);
    lv_obj_set_y(ui_LabelTime1, -26);
    lv_obj_set_align(ui_LabelTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime1, "16:00");
    lv_obj_set_style_text_align(ui_LabelTime1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime2 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelTime2, 45);
    lv_obj_set_height(ui_LabelTime2, 16);
    lv_obj_set_x(ui_LabelTime2, -33);
    lv_obj_set_y(ui_LabelTime2, -26);
    lv_obj_set_align(ui_LabelTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime2, "17:00");
    lv_obj_set_style_text_align(ui_LabelTime2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime3 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelTime3, 45);
    lv_obj_set_height(ui_LabelTime3, 16);
    lv_obj_set_x(ui_LabelTime3, 28);
    lv_obj_set_y(ui_LabelTime3, -26);
    lv_obj_set_align(ui_LabelTime3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime3, "18:00");
    lv_obj_set_style_text_align(ui_LabelTime3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime4 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelTime4, 45);
    lv_obj_set_height(ui_LabelTime4, 16);
    lv_obj_set_x(ui_LabelTime4, 92);
    lv_obj_set_y(ui_LabelTime4, -26);
    lv_obj_set_align(ui_LabelTime4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime4, "19:00");
    lv_obj_set_style_text_align(ui_LabelTime4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimeWea1 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelTimeWea1, 45);
    lv_obj_set_height(ui_LabelTimeWea1, 35);
    lv_obj_set_x(ui_LabelTimeWea1, -92);
    lv_obj_set_y(ui_LabelTimeWea1, 4);
    lv_obj_set_align(ui_LabelTimeWea1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeWea1, "Light Rain");
    lv_obj_set_style_text_align(ui_LabelTimeWea1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimeWea2 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelTimeWea2, 45);
    lv_obj_set_height(ui_LabelTimeWea2, 35);
    lv_obj_set_x(ui_LabelTimeWea2, -33);
    lv_obj_set_y(ui_LabelTimeWea2, 4);
    lv_obj_set_align(ui_LabelTimeWea2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeWea2, "Light Rain");
    lv_obj_set_style_text_align(ui_LabelTimeWea2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimeWea3 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelTimeWea3, 45);
    lv_obj_set_height(ui_LabelTimeWea3, 35);
    lv_obj_set_x(ui_LabelTimeWea3, 28);
    lv_obj_set_y(ui_LabelTimeWea3, 4);
    lv_obj_set_align(ui_LabelTimeWea3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeWea3, "Light Rain");
    lv_obj_set_style_text_align(ui_LabelTimeWea3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimeWea4 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelTimeWea4, 45);
    lv_obj_set_height(ui_LabelTimeWea4, 35);
    lv_obj_set_x(ui_LabelTimeWea4, 92);
    lv_obj_set_y(ui_LabelTimeWea4, 4);
    lv_obj_set_align(ui_LabelTimeWea4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeWea4, "Light Rain");
    lv_obj_set_style_text_align(ui_LabelTimeWea4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDegree1 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelDegree1, 45);
    lv_obj_set_height(ui_LabelDegree1, 16);
    lv_obj_set_x(ui_LabelDegree1, -92);
    lv_obj_set_y(ui_LabelDegree1, 31);
    lv_obj_set_align(ui_LabelDegree1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDegree1, "11°");
    lv_obj_set_style_text_align(ui_LabelDegree1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDegree2 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelDegree2, 45);
    lv_obj_set_height(ui_LabelDegree2, 16);
    lv_obj_set_x(ui_LabelDegree2, -33);
    lv_obj_set_y(ui_LabelDegree2, 31);
    lv_obj_set_align(ui_LabelDegree2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDegree2, "11°");
    lv_obj_set_style_text_align(ui_LabelDegree2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDegree3 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelDegree3, 45);
    lv_obj_set_height(ui_LabelDegree3, 16);
    lv_obj_set_x(ui_LabelDegree3, 28);
    lv_obj_set_y(ui_LabelDegree3, 31);
    lv_obj_set_align(ui_LabelDegree3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDegree3, "11°");
    lv_obj_set_style_text_align(ui_LabelDegree3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDegree4 = lv_label_create(ui_PanelWeaTimePre);
    lv_obj_set_width(ui_LabelDegree4, 45);
    lv_obj_set_height(ui_LabelDegree4, 16);
    lv_obj_set_x(ui_LabelDegree4, 92);
    lv_obj_set_y(ui_LabelDegree4, 31);
    lv_obj_set_align(ui_LabelDegree4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDegree4, "11°");
    lv_obj_set_style_text_align(ui_LabelDegree4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWeaDayPre = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelWeaDayPre, 240);
    lv_obj_set_height(ui_PanelWeaDayPre, 109);
    lv_obj_set_x(ui_PanelWeaDayPre, 0);
    lv_obj_set_y(ui_PanelWeaDayPre, 161);
    lv_obj_set_align(ui_PanelWeaDayPre, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWeaDayPre, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWeaDayPre, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWeaDayPre, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYesterday = lv_label_create(ui_PanelWeaDayPre);
    lv_obj_set_width(ui_LabelYesterday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYesterday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYesterday, -73);
    lv_obj_set_y(ui_LabelYesterday, -37);
    lv_obj_set_align(ui_LabelYesterday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelYesterday, "Yesterday");
    lv_obj_set_style_text_align(ui_LabelYesterday, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYesWea = lv_label_create(ui_PanelWeaDayPre);
    lv_obj_set_width(ui_LabelYesWea, 95);
    lv_obj_set_height(ui_LabelYesWea, 14);
    lv_obj_set_x(ui_LabelYesWea, 10);
    lv_obj_set_y(ui_LabelYesWea, -37);
    lv_obj_set_align(ui_LabelYesWea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelYesWea, "Sunny");
    lv_obj_set_style_text_align(ui_LabelYesWea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYesTem = lv_label_create(ui_PanelWeaDayPre);
    lv_obj_set_width(ui_LabelYesTem, 57);
    lv_obj_set_height(ui_LabelYesTem, 14);
    lv_obj_set_x(ui_LabelYesTem, 82);
    lv_obj_set_y(ui_LabelYesTem, -37);
    lv_obj_set_align(ui_LabelYesTem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelYesTem, "14/2°C");
    lv_obj_set_style_text_align(ui_LabelYesTem, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelToday = lv_label_create(ui_PanelWeaDayPre);
    lv_obj_set_width(ui_LabelToday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelToday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelToday, -72);
    lv_obj_set_y(ui_LabelToday, -6);
    lv_obj_set_align(ui_LabelToday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelToday, "Today");
    lv_obj_set_style_text_align(ui_LabelToday, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTomorrow = lv_label_create(ui_PanelWeaDayPre);
    lv_obj_set_width(ui_LabelTomorrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTomorrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTomorrow, -73);
    lv_obj_set_y(ui_LabelTomorrow, 26);
    lv_obj_set_align(ui_LabelTomorrow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTomorrow, "Tomorrow");
    lv_obj_set_style_text_align(ui_LabelTomorrow, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTodayWea = lv_label_create(ui_PanelWeaDayPre);
    lv_obj_set_width(ui_LabelTodayWea, 95);
    lv_obj_set_height(ui_LabelTodayWea, 14);
    lv_obj_set_x(ui_LabelTodayWea, 8);
    lv_obj_set_y(ui_LabelTodayWea, -6);
    lv_obj_set_align(ui_LabelTodayWea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTodayWea, "Rain");
    lv_obj_set_style_text_align(ui_LabelTodayWea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTomWea = lv_label_create(ui_PanelWeaDayPre);
    lv_obj_set_width(ui_LabelTomWea, 95);
    lv_obj_set_height(ui_LabelTomWea, 14);
    lv_obj_set_x(ui_LabelTomWea, 9);
    lv_obj_set_y(ui_LabelTomWea, 26);
    lv_obj_set_align(ui_LabelTomWea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTomWea, "Rain");
    lv_obj_set_style_text_align(ui_LabelTomWea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTodayTem = lv_label_create(ui_PanelWeaDayPre);
    lv_obj_set_width(ui_LabelTodayTem, 57);
    lv_obj_set_height(ui_LabelTodayTem, 14);
    lv_obj_set_x(ui_LabelTodayTem, 82);
    lv_obj_set_y(ui_LabelTodayTem, -6);
    lv_obj_set_align(ui_LabelTodayTem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTodayTem, "14/2°C");
    lv_obj_set_style_text_align(ui_LabelTodayTem, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTomTem = lv_label_create(ui_PanelWeaDayPre);
    lv_obj_set_width(ui_LabelTomTem, 57);
    lv_obj_set_height(ui_LabelTomTem, 14);
    lv_obj_set_x(ui_LabelTomTem, 82);
    lv_obj_set_y(ui_LabelTomTem, 26);
    lv_obj_set_align(ui_LabelTomTem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTomTem, "14/2°C");
    lv_obj_set_style_text_align(ui_LabelTomTem, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenWeather, ui_event_ScreenWeather, LV_EVENT_ALL, NULL);

}
