// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
void ui_SrceenHome_load_date(void);
lv_obj_t *ui_ScreenHome;
lv_obj_t *ui_PanelElectric;
lv_obj_t *ui_ArcElectric;
lv_obj_t *ui_LabelElectric;
lv_obj_t *ui_ImageElectric;
lv_obj_t *ui_PanelDate;
// lv_obj_t *ui_LabelTime;
lv_obj_t *ui_LabelHour;
lv_obj_t *ui_LabelMinute;
lv_obj_t *ui_LabelSymbol;
lv_obj_t *ui_LabelDate;
lv_obj_t *ui_LabelWeek;
lv_obj_t *ui_PanelStep;
lv_obj_t *ui_ImageStep;
lv_obj_t *ui_LabelStep;
void ui_event_SliderStep(lv_event_t *e);
lv_obj_t *ui_SliderStep;
lv_obj_t *ui_PanelWeather;
void ui_event_ArcTem(lv_event_t *e);
lv_obj_t *ui_ArcTem;
lv_obj_t *ui_ImageTem;
lv_obj_t *ui_LabelTem;
void ui_event_ArcHum(lv_event_t *e);
lv_obj_t *ui_ArcHum;
lv_obj_t *ui_ImageHum;
lv_obj_t *ui_LabelHum;
void ui_event_ArcAQI(lv_event_t *e);
lv_obj_t *ui_ArcAQI;
lv_obj_t *ui_ImageAQI;
lv_obj_t *ui_LabelAQI;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_flash[2] = {&ui_img_flash2_png, &ui_img_flash3_png};
const lv_img_dsc_t *ui_imgset_temp[1] = {&ui_img_temp2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SliderStep(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_arc_set_text_value(ui_LabelStep, target, "", "");
    }
}
void ui_event_ArcTem(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_arc_set_text_value(ui_LabelTem, target, "", "°");
    }
}
void ui_event_ArcHum(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_arc_set_text_value(ui_LabelHum, target, "", "%");
    }
}
void ui_event_ArcAQI(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_arc_set_text_value(ui_LabelAQI, target, "", "");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenHome_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenHome);
}
