// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
// #include "..main.h"
#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenHome
void ui_SrceenHome_load_date(void);
void ui_ScreenHome_screen_init(void);
extern lv_obj_t *ui_ScreenHome;
extern lv_obj_t *ui_PanelElectric;
extern lv_obj_t *ui_ArcElectric;
extern lv_obj_t *ui_LabelElectric;
extern lv_obj_t *ui_ImageElectric;
extern lv_obj_t *ui_PanelDate;
// extern lv_obj_t *ui_LabelTime;
extern lv_obj_t *ui_LabelSymbol;
extern lv_obj_t *ui_LabelHour;
extern lv_obj_t *ui_LabelMinute;
extern lv_obj_t *ui_LabelDate;
extern lv_obj_t *ui_LabelWeek;
extern lv_obj_t *ui_PanelStep;
extern lv_obj_t *ui_ImageStep;
extern lv_obj_t *ui_LabelStep;
void ui_event_SliderStep( lv_event_t * e);
extern lv_obj_t *ui_SliderStep;
extern lv_obj_t *ui_PanelWeather;
void ui_event_ArcTem( lv_event_t * e);
extern lv_obj_t *ui_ArcTem;
extern lv_obj_t *ui_ImageTem;
extern lv_obj_t *ui_LabelTem;
void ui_event_ArcHum( lv_event_t * e);
extern lv_obj_t *ui_ArcHum;
extern lv_obj_t *ui_ImageHum;
extern lv_obj_t *ui_LabelHum;
void ui_event_ArcAQI( lv_event_t * e);
extern lv_obj_t *ui_ArcAQI;
extern lv_obj_t *ui_ImageAQI;
extern lv_obj_t *ui_LabelAQI;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_flash3_png);   // assets\flash3.png
LV_IMG_DECLARE( ui_img_step_png);   // assets\step.png
LV_IMG_DECLARE( ui_img_temp2_png);   // assets\temp2.png
LV_IMG_DECLARE( ui_img_hum_png);   // assets\hum.png
LV_IMG_DECLARE( ui_img_aqi_png);   // assets\AQI.png
LV_IMG_DECLARE( ui_img_flash2_png);   // assets\flash2.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
