// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_ScreenAbout_screen_init(void)
{
    ui_ScreenAbout = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAbout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAbout, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAbout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageYogurt = lv_img_create(ui_ScreenAbout);
    lv_img_set_src(ui_ImageYogurt, &ui_img_yogurt_png);
    lv_obj_set_width(ui_ImageYogurt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageYogurt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageYogurt, -51);
    lv_obj_set_y(ui_ImageYogurt, 97);
    lv_obj_set_align(ui_ImageYogurt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageYogurt, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageYogurt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelYogurt = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelYogurt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYogurt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYogurt, 35);
    lv_obj_set_y(ui_LabelYogurt, 108);
    lv_obj_set_align(ui_LabelYogurt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelYogurt, "By Yogurt");

    ui_LabelName = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelName, 240);
    lv_obj_set_height(ui_LabelName, 20);
    lv_obj_set_x(ui_LabelName, -3);
    lv_obj_set_y(ui_LabelName, -100);
    lv_obj_set_align(ui_LabelName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelName, "Smart Home Watch");
    lv_obj_set_style_text_align(ui_LabelName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelName, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVersion = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelVersion, 100);
    lv_obj_set_height(ui_LabelVersion, 14);
    lv_obj_set_x(ui_LabelVersion, 0);
    lv_obj_set_y(ui_LabelVersion, -63);
    lv_obj_set_align(ui_LabelVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVersion, "Version:1.0.0");
    lv_obj_set_style_text_align(ui_LabelVersion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProcessor = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelProcessor, 180);
    lv_obj_set_height(ui_LabelProcessor, 14);
    lv_obj_set_x(ui_LabelProcessor, 0);
    lv_obj_set_y(ui_LabelProcessor, -40);
    lv_obj_set_align(ui_LabelProcessor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProcessor, "Processor:ESP32");
    lv_obj_set_style_text_align(ui_LabelProcessor, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenAbout, ui_event_ScreenAbout, LV_EVENT_ALL, NULL);

}
