// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "web_get.h"

void ui_ScreenCalendar_screen_init(void)
{
    ui_ScreenCalendar = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCalendar, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Calendar = lv_calendar_create(ui_ScreenCalendar);
    lv_calendar_set_today_date(ui_Calendar, year, month, day);
    lv_calendar_set_showed_date(ui_Calendar, year, month);
    lv_obj_t *ui_Calendar_header = lv_calendar_header_arrow_create(ui_Calendar);
    lv_obj_set_width(ui_Calendar, 240);
    lv_obj_set_height(ui_Calendar, 280);
    lv_obj_set_align(ui_Calendar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Calendar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Calendar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenCalendar, ui_event_ScreenCalendar, LV_EVENT_ALL, NULL);
}

