// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_ScreenRemote_screen_init(void)
{
    ui_ScreenRemote = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenRemote, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelMusic = lv_obj_create(ui_ScreenRemote);
    lv_obj_set_width(ui_PanelMusic, 240);
    lv_obj_set_height(ui_PanelMusic, 140);
    lv_obj_set_x(ui_PanelMusic, 0);
    lv_obj_set_y(ui_PanelMusic, -70);
    lv_obj_set_align(ui_PanelMusic, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageMusicIcon = lv_img_create(ui_PanelMusic);
    lv_img_set_src(ui_ImageMusicIcon, &ui_img_netease_png);
    lv_obj_set_width(ui_ImageMusicIcon, 48);
    lv_obj_set_height(ui_ImageMusicIcon, 48);
    lv_obj_set_x(ui_ImageMusicIcon, -70);
    lv_obj_set_y(ui_ImageMusicIcon, -31);
    lv_obj_set_align(ui_ImageMusicIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMusicIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMusicIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMusic = lv_label_create(ui_PanelMusic);
    lv_obj_set_width(ui_LabelMusic, 100);
    lv_obj_set_height(ui_LabelMusic, 32);
    lv_obj_set_x(ui_LabelMusic, 23);
    lv_obj_set_y(ui_LabelMusic, -33);
    lv_obj_set_align(ui_LabelMusic, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMusic, "Music");
    lv_obj_set_style_text_align(ui_LabelMusic, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMusic, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonNext = lv_imgbtn_create(ui_PanelMusic);
    lv_imgbtn_set_src(ui_ImgButtonNext, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_next2_png, NULL);
    lv_obj_set_width(ui_ImgButtonNext, 32);
    lv_obj_set_height(ui_ImgButtonNext, 32);
    lv_obj_set_x(ui_ImgButtonNext, 70);
    lv_obj_set_y(ui_ImgButtonNext, 25);
    lv_obj_set_align(ui_ImgButtonNext, LV_ALIGN_CENTER);

    ui_ImgButtonPause = lv_imgbtn_create(ui_PanelMusic);
    lv_imgbtn_set_src(ui_ImgButtonPause, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_pause_png, NULL);
    lv_obj_set_width(ui_ImgButtonPause, 32);
    lv_obj_set_height(ui_ImgButtonPause, 32);
    lv_obj_set_x(ui_ImgButtonPause, 0);
    lv_obj_set_y(ui_ImgButtonPause, 25);
    lv_obj_set_align(ui_ImgButtonPause, LV_ALIGN_CENTER);

    ui_ImgButtonPrior = lv_imgbtn_create(ui_PanelMusic);
    lv_imgbtn_set_src(ui_ImgButtonPrior, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_prior_png, NULL);
    lv_obj_set_width(ui_ImgButtonPrior, 32);
    lv_obj_set_height(ui_ImgButtonPrior, 32);
    lv_obj_set_x(ui_ImgButtonPrior, -70);
    lv_obj_set_y(ui_ImgButtonPrior, 25);
    lv_obj_set_align(ui_ImgButtonPrior, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ScreenRemote, ui_event_ScreenRemote, LV_EVENT_ALL, NULL);

}
