// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "main.h"

TimerHandle_t stop_watch;
int stop_watch_second = 0;
int stop_watch_minute = 0;
char stop_time_print[6] = "00:00";

void ui_ScreenStopwatch_screen_init(void)
{
    ui_ScreenStopwatch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenStopwatch, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_ArcMin = lv_arc_create(ui_ScreenStopwatch);
    lv_obj_set_width(ui_ArcMin, 150);
    lv_obj_set_height(ui_ArcMin, 150);
    lv_obj_set_x(ui_ArcMin, 4);
    lv_obj_set_y(ui_ArcMin, -40);
    lv_obj_set_align(ui_ArcMin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcMin, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcMin, 0, 60);
    lv_arc_set_value(ui_ArcMin, 0);
    lv_arc_set_bg_angles(ui_ArcMin, 0, 360);
    lv_arc_set_rotation(ui_ArcMin, 270);
    lv_obj_set_style_arc_color(ui_ArcMin, lv_color_hex(0x251E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcMin, lv_color_hex(0x251E1E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcMin, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_ArcMin, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcMin, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcMin, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcMin, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcSec = lv_arc_create(ui_ScreenStopwatch);
    lv_obj_set_width(ui_ArcSec, 180);
    lv_obj_set_height(ui_ArcSec, 180);
    lv_obj_set_x(ui_ArcSec, 4);
    lv_obj_set_y(ui_ArcSec, -40);
    lv_obj_set_align(ui_ArcSec, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcSec, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcSec, 0, 60);
    lv_arc_set_value(ui_ArcSec, 0);
    lv_arc_set_bg_angles(ui_ArcSec, 0, 360);
    lv_arc_set_rotation(ui_ArcSec, 270);
    lv_obj_set_style_arc_color(ui_ArcSec, lv_color_hex(0x251E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcSec, lv_color_hex(0x251E1E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSec, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcSec, lv_color_hex(0xBC2F2F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcSec, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ArcSec, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcSec, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcSec, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcSec, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelStopTime = lv_label_create(ui_ScreenStopwatch);
    lv_obj_set_width(ui_LabelStopTime, 100);
    lv_obj_set_height(ui_LabelStopTime, 24);
    lv_obj_set_x(ui_LabelStopTime, 4);
    lv_obj_set_y(ui_LabelStopTime, -40);
    lv_obj_set_align(ui_LabelStopTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStopTime, "00:00");
    lv_obj_set_style_text_align(ui_LabelStopTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStopTime, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchStop = lv_switch_create(ui_ScreenStopwatch);
    lv_obj_set_width(ui_SwitchStop, 80);
    lv_obj_set_height(ui_SwitchStop, 50);
    lv_obj_set_x(ui_SwitchStop, 12);
    lv_obj_set_y(ui_SwitchStop, 92);
    lv_obj_set_align(ui_SwitchStop, LV_ALIGN_CENTER);

    ui_ImgButtonAgain = lv_imgbtn_create(ui_ScreenStopwatch);
    lv_imgbtn_set_src(ui_ImgButtonAgain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_again2_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonAgain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_again2_png, NULL);
    lv_obj_set_width(ui_ImgButtonAgain, 64);
    lv_obj_set_height(ui_ImgButtonAgain, 64);
    lv_obj_set_x(ui_ImgButtonAgain, -73);
    lv_obj_set_y(ui_ImgButtonAgain, 91);
    lv_obj_set_align(ui_ImgButtonAgain, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_SwitchStop, ui_event_SwitchStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonAgain, ui_event_ImgButtonAgain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenStopwatch, ui_event_ScreenStopwatch, LV_EVENT_ALL, NULL);
}

void ui_ScreenStopwatch_load_data(void)
{
    lv_arc_set_value(ui_ArcMin, stop_watch_minute);
    lv_arc_set_value(ui_ArcSec, stop_watch_second);
    lv_label_set_text(ui_LabelStopTime, stop_time_print);
    lv_scr_load(ui_ScreenStopwatch);
}

void stop_watch_callback(TimerHandle_t pxTimer)
{
    stop_watch_second++;
    if (stop_watch_second > 59)
    {
        stop_watch_second = 0;
        stop_watch_minute++;
    }
    if (stop_watch_second < 10 && stop_watch_minute < 10)
    {
        sprintf(stop_time_print, "0%d:0%d", stop_watch_minute, stop_watch_second);
    }
    else if (stop_watch_second < 10)
    {
        sprintf(stop_time_print, "%d:0%d", stop_watch_minute, stop_watch_second);
    }
    else if (stop_watch_minute < 10)
    {
        sprintf(stop_time_print, "0%d:%d", stop_watch_minute, stop_watch_second);
    }
    else
    {
        sprintf(stop_time_print, "%d:%d", stop_watch_minute, stop_watch_second);
    }
}